server:
  port: 90

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schoolemploy?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  pattern:
    console: '%d{HH:mm:ss.SSS}%clr(%-5level) --- [%-15thread]%cyan(%-50logger{50}):%msg%n'

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 发送邮件配置
mail:
  # 发件人地址
  user: 1228088700@qq.com
  # 发件人密码
  password: kiyhbsdyewwdbabc








